version: "3"

services:
   runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner-1
    restart: always
    network_mode: bridge
    volumes:
      - /opt/docker/volume/gitlab-runner-1/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    mem_limit: 512m
    mem_reservation: 128m

